config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pets
  get 'home' => 'pets#home'

  root to: "pets#home"
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  has_many :photos

  bitmask :colour, as: [:black, :white, :tan, :grey, :brown, :yellow, :red]
  enum sex: [:male, :female, :unknown]
  scope :by_sex, -> (sex) { where(sex: sex.to_sym) }
  enum species: [:dog, :cat, :other]
  scope :by_species, -> (species) { where(species: species.to_sym) }
  enum location: [:SW, :SE, :NE, :NW]
  scope :by_location, -> (location) { where(location: location.to_sym) }
  enum status: [:lost, :found]
  scope :by_status, -> (status) { where(status: status.to_sym) }

  validates :user, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :pet
  validates :pet, presence: true
  has_attached_file :image
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def home
  end

  def index
    @pets = Pet.all
    authorize Pet
  end

  def show
    @pet = Pet.find(params[:id])
    authorize @pet
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = current_user.pets.build(pet_params)
    authorize @pet
    if @pet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(param[:id])
    authorize @pet
  end

  def update
    @pet.update(pet_params)
    authorize @pet
    redirect_to root_path
  end

  def delete
    Pet.find(params[:id]).destroy
    authorize @pet
    redirect_to root_path
  end

  private

  def pet_params
    params.require(:pet).permit(:species, :name, :sex, :colour, :identification, :location,
                                :description, :status, :photos)
  end

  def set_pet
    @pet = current_user.pets.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
  def display_pet_name(pet)
    if pet.name.blank?
      'Unknown'
    else
      pet.name
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Pet Finder" %></title>

    <%= stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">

        <!-- For small to medium devices -->
        <div class="hide-for-large-up">
          <nav class="tab-bar sticky">
            <section class="left">
              <a class="left-off-canvas-toggle menu-icon" href=""><span></span></a>
            </section>
          </nav>

          <aside class="left-off-canvas-menu">
            <ul class="off-canvas-list">

              <% if user_signed_in? %>
                <li><label><%= current_user.email %></label></li>
                <li> <%= link_to 'Home', root_path %></li>
                <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                <li class="has-submenu"><a href="">Profile</a>
                  <ul class="left-submenu">
                    <li class="back"><a href="#">Back</a></li>
                    <li><label>Profile</label></li>
                    <li><%= link_to 'Change Password', edit_user_registration_path %></li>
                    <li><%= link_to 'Edit Pet Report', edit_pet_path(:id) %></li>
                    <ul class="left-submenu">
                      <li class="back"><a href="#">Back</a></li>
                    </ul>
                  </ul>
                </li>

              <% else %>
                <li><label>Welcome</label></li>
                <li> <%= link_to 'Home', root_path %></li>
                <li> <%= link_to 'Sign In', new_user_session_path, method: :get %></li>
                <li> <%= link_to 'Register', new_user_registration_path, method: :get %></li>
              <% end %>

              <li> <%= link_to 'Lost a Pet?', new_pet_path(:id), method: :get %></li>
              <li> <%= link_to 'Found a Pet?', new_pet_path(:id), method: :get %></li>

              <li class="has-submenu"><a href="">Lost/Found Database</a>
                <ul class="left-submenu">
                  <li class="back"><a href="#">Back</a></li>
                  <li><label>Profile</label></li>
                  <li> <%= link_to 'Dog Database', pets_path %></li>
                  <li> <%= link_to 'Cat Database', pets_path %></li>
                  <li> <%= link_to 'Other Pet Database', pets_path %></li>
                  <ul class="left-submenu">
                    <li class="back"><a href="#">Back</a></li>
                  </ul>
                </ul>
              </li>
              <li> <%= link_to 'Contact', root_path %></li>
            </ul>
          </aside>

          <div class="row">
            <div class="small-12 column text-center">
              <div id="logo">
                <h1>
                  <a href="<%= root_path %>">
                  <%= image_tag 'logo.png', class: 'mylogo' %>
                  </a>
                </h1>
              </div>
            </div>
          </div>
        </div>

        <!-- For large and up devices -->
        <div class="row hide-for-small hide-for-medium large-top-bar">
          <div class="small-3 columns">
            <a href="<%= root_path %>">
                     <%= image_tag 'logo.png', class: 'mylogo' %>
                    </a>
          </div>
          <div class"small-9 columns" style="
            padding-top: 26px;
            text-align: right;
          ">
            <a> <%= link_to 'Home', root_path, class: 'button-home' %> </a>
            <a> <%= link_to 'Lost a Pet?', new_pet_path(:id), class: 'button-menu' %> </a>
            <a> <%= link_to 'Found a Pet?', new_pet_path(:id), class: 'button-menu' %> </a>
            <a> <%= link_to 'Contact', root_path, class: 'button-menu' %> </a>

            <% if user_signed_in? %>
             <button href="#" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="button dropdown">Profile</button><br>
            <ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true">
              <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              <li><%= link_to 'Change Password', edit_user_registration_path %></li>
              <li><%= link_to 'Edit Pet Report', edit_pet_path(:id) %></li>
            </ul>
            <% else %>
              <a> <%= link_to 'Sign In/Register', new_user_session_path, method: :get, class: 'button-menu' %></a>
            <% end %>
          </div>
        </div>

         <section class="main-section">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
            <%= yield %>
        </section>

        <a class="exit-off-canvas"></a>
      </div> <!-- .inner-wrap -->
    </div> <!-- .off-canvas-wrap -->

  </body>
</html>

app/views/pets/home.html.erb
<div class="row">
  <div class="small-11 small-centered medium-11 large-12 columns panel">

    <!-- For small and medium devices -->
    <div class="row hide-for-large-up">
      <div class="small-11 small-centered medium-11 medium-centered columns text-center">
        <h1>Welcome to Pet Finder Calgary</h1>
        <h2>sidfh  dfsh  fhsd huf sdhuf usdiof sudiof sdfhuoidsf dsufh dsufhusdifh udsfh usdfh usdfh sdhf sdfusdf</h2>
        <%= link_to 'Lost a Pet?', new_pet_path, class: 'button expand' %>
        <%= link_to 'Found a Pet?', new_pet_path, class: 'button expand' %>
      </div>
    </div>

    <!-- For large devices only -->
    <div class="row hide-for-small hide-for-medium">
      <div class="large-8 columns">
        <h1>Welcome to Pet Finder Calgary</h1>
        <h2>sidfh  dfsh  fhsd huf sdhuf usdiof sudiof sdfhuoidsf dsufh dsufhusdifh udsfh usdfh usdfh sdhf sdfusdf</h2>
      </div>
      <div class="large-4 columns text-center header-panel-buttons">
        <%= link_to 'Lost a Pet?', root_path, class: 'button expand' %>
          <%= link_to 'Found a Pet?', root_path, class: 'button expand' %>
      </div>
    </div>
  </div>
</div>

<!-- For small devices only -->

<div class="row hide-for-medium-up">
  <div class="small-11 small-centered columns panel small-data-panel">
    <a href="<%= pets_path %>">
      <%= image_tag 'DogData.png', class: 'data-photo' %>
    </a>
      <h3>Dog Database</h3>
      <p>Search for all Lost or Found Dogs in the Calgary area.</p>
  </div>

  <div class="small-11 small-centered columns panel small-data-panel">
    <a href="<%= pets_path %>">
      <%= image_tag 'CatData.png', class: 'data-photo' %>
    </a>
    <h3>Cat Database</h3>
    <p>Search for all Lost or Found Cats in the Calgary area.</p>
  </div>

  <div class="small-11 small-centered columns panel small-data-panel">
    <a href="<%= pets_path %>">
      <%= image_tag 'OtherData.png', class: 'data-photo' %>
    </a>
    <h3>Other Pets Database</h3>
    <p>Search for all other Lost or Found Pets in the Calgary area.</p>
  </div>
</div>

<div class="row step-by-step-style hide-for-medium-up">
  <div class="small-12 panel columns how-it-works-panel-small">
    <h2>What to do if you have lost a pet</h2>
    <div class="row">
      <div class="small-2 columns">
        <h3>1</h3>
      </div>
      <div class="small-10 columns">
        <p>Search for your pet in the <%= link_to 'Lost and Found Pets', new_pet_path %> database.</p>
      </div>
    </div>
    <div class="row">
      <div class="small-2 columns">
        <h3>2</h3>
      </div>
      <div class="small-10 columns">
        <p>If your pet has not been reported as found fill out a <%= link_to 'Lost Pet Report', new_pet_path %>.</p>
      </div>
    </div>
    <div class="row">
      <div class="small-2 columns">
        <h3>3</h3>
      </div>
      <div class="small-10 columns">
        <p>Upon <%= link_to 'registration', new_user_registration_path %> you may select to receive notifications alerting you when a pet has been found that matches your Lost Pet Profile.</p>
      </div>
    </div>

    <h2>What to do if you have found a pet</h2>
    <div class="row">
      <div class="small-2 columns">
        <h3>1</h3>
      </div>
      <div class="small-10 columns">
        <p>Search the <%= link_to 'Lost and Found Pets', new_pet_path %> database to see if the pet has been reported as lost.</p>
      </div>
    </div>
    <div class="row">
      <div class="small-2 columns">
        <h3>2</h3>
      </div>
      <div class="small-10 columns">
        <p>If the pet has not been reported fill out a <%= link_to 'Found Pet Report', new_pet_path %>.</p>
      </div>
    </div>
  </div>
</div>

<!-- For medium and up devices -->
<div class="row hide-for-small med-data-panel">
  <div class="medium-11 medium-centered large-12 columns">
    <ul class="medium-block-grid-3">
      <li>
        <div class="panel database-panel">
          <a href="<%= pets_path %>">
            <%= image_tag 'DogData.png', class: 'data-photo' %>
          </a>
          <h3>Dog Database</h3>
          <p>Search for all Lost or Found Dogs in the Calgary area.</p>
        </div>
      </li>
      <li>
        <div class="panel database-panel">
          <a href="<%= pets_path %>">
            <%= image_tag 'CatData.png', class: 'data-photo' %>
          </a>
          <h3>Dog Database</h3>
          <p>Search for all Lost or Found Dogs in the Calgary area.</p>
        </div>
      </li>
      <li>
        <div class="panel database-panel">
          <a href="<%= pets_path %>">
            <%= image_tag 'OtherData.png', class: 'data-photo' %>
          </a>
          <h3>Dog Database</h3>
          <p>Search for all Lost or Found Dogs in the Calgary area.</p>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="panel hide-for-small how-it-works-panel-medium-up">
  <div class="row">
    <div class="small-6 columns">
      <h2>What to do if you have lost a pet</h2>
    </div>
    <div class="small-6 columns">
      <h2>What to do if you have found a pet</h2>
    </div>
  </div>

  <div class="row">
    <div class="small-1 columns">
      <h3>1</h3>
    </div>
    <div class="small-5 columns">
      <p>Search for your pet in the <%= link_to 'Lost and Found Pets', new_pet_path %> database.</p>
    </div>
    <div class="small-1 columns">
      <h3>1</h3>
    </div>
    <div class="small-5 columns">
      <p>Search the <%= link_to 'Lost and Found Pets', new_pet_path %> database to see if the pet has been reported as lost.</p>
    </div>
  </div>
  <div class="row">
    <div class="small-1 columns">
      <h3>2</h3>
    </div>
    <div class="small-5 columns">
      <p>If your pet has not been reported as found fill out a <%= link_to 'Lost Pet Report', new_pet_path %>.</p>
    </div>
    <div class="small-1 columns">
      <h3>2</h3>
    </div>
    <div class="small-5 columns">
      <p>If the pet has not been reported fill out a <%= link_to 'Found Pet Report', new_pet_path %>.</p>
    </div>
  </div>
  <div class="row">
    <div class="small-1 columns">
      <h3>3</h3>
    </div>
    <div class="small-5 columns end">
      <p>Upon <%= link_to 'registration', new_user_registration_path %> you may select to receive notifications alerting you when a pet has been found that matches your Lost Pet Profile.</p>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class="row">
  <div class="small-11 small-centered medium-11 large-12 columns">
    <div class="panel database-panel">
      <ul class="tabs" data-tab>
        <li class="tab-title active"><a href="#panel1">Lost</a></li>
        <li class="tab-title"><a href="#panel2">Found</a></li>
      </ul>
      <div class="tabs-content">
        <!-- Lost Tab -->

        <div class="content active" id="panel1">

          <!-- for small and medium devices -->
          <div class="hide-for-large-up">
            <form>
              <div class="row">
                <div class="small-11 small-centered medium-11 columns">
                  <div class="row collapse postfix round" style="border-color: transparent;">
                    <div class="small-9 columns">
                      <input type="text" placeholder="Search by keyword(s)">
                    </div>
                    <div class="small-3 columns">
                      <a href="#" class="button postfix">Search</a>
                    </div>
                  </div>
                  <div class="filter-button">
                    <button href="#" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="button expand dropdown filter-button">Filters</button><br>
                    <ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true">
                      <li><a href="#">Gender</a></li>
                      <li><a href="#">Colour</a></li>
                      <li><a href="#">Location</a></li>
                    </ul>
                  </div>
                  <% @pets.each do |pet| %>
                    <div class="panel search-panel">
                      <!-- for small devices -->
                      <div class="hide-for-medium-up">
                        <!-- pet photos -->
                        <% pet.photos.each do |photo| %>
                          <%= image_tag photo.image.url %>
                        <% end %>
                        <%= image_tag 'catdefault.png' %>
                        <!-- pet descriptions -->
                        <h3><%= display_pet_name(pet) %></h3>
                        <p><%= pet.description %></p>
                      </div>
                      <!-- for medium devices -->
                      <div class="hide-for-small hide-for-large-up">
                        <div class="row">
                          <div class="small-5 columns">
                            <!-- pet photos -->
                            <%= image_tag 'catdefault.png' %>
                          </div>
                          <div class="small-7 columns">
                            <!-- pet descriptions -->
                            <h3>Name</h3>
                            <p>Description sdhf uiosfh suhfushf usdhf usdfh usdf.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </form>
          </div>

          <!-- for large devices -->
          <div class="hide-for-small hide-for-medium">
            <div class="large-12 columns">
              <div class="row">
                <div class="small-8 columns">
                  <div class="row collapse postfix round" style="border-color: transparent;">
                    <div class="small-9 columns">
                      <input type="text" placeholder="Search by keyword(s)">
                    </div>
                    <div class="small-3 columns">
                      <a href="#" class="button postfix">Search</a>
                    </div>
                  </div>
                </div>
                <div class="small-4 columns">
                  <div class="filter-button">
                    <button href="#" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="button expand dropdown filter-button-large">Filters</button><br>
                    <ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true">
                      <li><a href="#">Gender</a></li>
                      <li><a href="#">Colour</a></li>
                      <li><a href="#">Area</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="small-6 columns">
                  <div class="panel search-panel">
                    <div class="row">
                      <div class="small-5 columns">
                        <!-- pet photos -->
                        <a href="<%= pet_path(:id) %>">
                          <%= image_tag 'testphoto.png', class: 'photo' %>
                        </a>
                      </div>
                      <div class="small-7 columns">
                        <!-- pet descriptions -->
                        <h3>Name</h3>
                        <p>Description sdhf uiosfh suhfushf usdhf usdfh usdf.</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-6 columns">
                  <div class="panel search-panel">
                    <div class="row">
                      <div class="small-5 columns">
                        <!-- pet photos -->
                        <a href="<%= pet_path(:id) %>">
                          <%= image_tag 'testphoto.png', class: 'photo' %>
                        </a>
                      </div>
                      <div class="small-7 columns">
                        <!-- pet descriptions -->
                        <h3>Name</h3>
                        <p>Description sdhf uiosfh suhfushf usdhf usdfh usdf.</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div> <!-- closes Lost tab -->

        <!-- Found Tab -->
        <div class="content" id="panel2">

          <!-- for small and medium devices -->
          <div class="hide-for-large-up">
            <form>
              <div class="row">
                <div class="small-11 small-centered medium-11 columns">
                  <div class="row collapse postfix round" style="border-color: transparent;">
                    <div class="small-9 columns">
                      <input type="text" placeholder="Search by keyword(s)">
                    </div>
                    <div class="small-3 columns">
                      <a href="#" class="button postfix">Search</a>
                    </div>
                  </div>
                  <div class="filter-button">
                    <button href="#" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="button expand dropdown filter-button">Filters</button><br>
                    <ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true">
                      <li><a href="#">Gender</a></li>
                      <li><a href="#">Colour</a></li>
                      <li><a href="#">Area</a></li>
                    </ul>
                  </div>
                  <!-- add @pets.each do |pet| here -->
                    <div class="panel search-panel">
                      <!-- for small devices -->
                      <div class="hide-for-medium-up">
                        <!-- pet photos -->
                        <a href="<%= pet_path(:id) %>">
                          <%= image_tag 'testphoto.png', class: 'photo' %>
                        </a>
                        <!-- pet descriptions -->
                        <h3>Name</h3>
                        <p>Description sdhf uiosfh suhfushf usdhf usdfh usdf.</p>
                      </div>
                      <!-- for medium devices -->
                      <div class="hide-for-small hide-for-large-up">
                        <div class="row">
                          <div class="small-5 columns">
                            <!-- pet photos -->
                            <a href="<%= pet_path(:id) %>">
                              <%= image_tag 'testphoto.png', class: 'photo' %>
                            </a>
                          </div>
                          <div class="small-7 columns">
                            <!-- pet descriptions -->
                            <h3>Name</h3>
                            <p>Description sdhf uiosfh suhfushf usdhf usdfh usdf.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <!-- end -->
            </form>
          </div>
        </div> <!-- closes Found tab -->
      </div>
    </div>
  </div>
</div>
<% console %>

app/views/pets/new.html.erb
<div class="row">
  <div class="small-11 small-centered medium-11 large-12 columns panel">
    <div class="row">
      <div class="small-11 small-centered medium-11 large-8 columns">
        <h1 class="text-center">Lost/Found Pet Report</h1>
        <p>* indicates required fields</p>
        <%= simple_form_for @pet do |f| %>
          <div class="row">
            <div class="small-4 columns">
              <%= f.input :status, collection: ['lost', 'found'], prompt: 'Select one' %>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-4 columns">
              <%= f.input :species, collection: [ "dog", "cat", "other" ], prompt: "Select one" %>
            </div>
            <div class="medium-8 columns">
                <%= f.input :name, label: 'Name (if known)', placeholder: 'Pet name' %>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-3 large-3 columns">
              <%= f.input :sex, collection: [ "male", "female", "unknown" ], prompt: "Select one" %>
            </div>
            <div class="medium-9 large-9 columns">
              <label>* Colour (select ALL that apply)</label>
              <%= f.collection_check_boxes :colour, [['black', image_tag('black.png')], ['white', image_tag('white.png')], ['tan', image_tag('tan.png')], ['grey', image_tag('grey.png')], ['brown', image_tag('brown.png')], ['yellow', image_tag('yellow.png')], ['red', image_tag('red.png')]], :first, :last,
                    {:item_wrapper_class => 'checkbox_container'} %>
            </div>
          </div>
          <div class="row">
            <div class="medium-8 columns">
              <%= f.input :identification, label: 'Identification (optional)', placeholder: 'Tag number, tattoo, microchip ID...' %>
            </div>
            <div class="medium-4 columns">
              <%= f.input :location, label: 'Lost/Found location', collection: ["NW", "NE", "SW", "SE"], prompt: "Select one" %>
            </div>
          </div>
          <div class="row">
            <div class="small-12 columns">
              <%= f.input :description, placeholder: 'Include general appearance (breed etc.), exact location where lost/found, temperament, distingishing features ect.', as: :text %>
          </div>
          <div class="row">
            <div class="small-12 columns">
              <%= f.input :photos, label: 'Photo', as: :file %>
              <%= f.button :submit %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>